server:
  port: 8082
                                       
okta:
  oauth2:
    issuer: https://dev-239735.okta.com/oauth2/default
    clientId: 0oauljsxLe61N8R784x5
#    clientSecret: W6zMy8fDnerC54u4bZiw6BkNjLMmU3XXnLwJqytG